package com.jslh.dao.mapper;

import com.jslh.model.SysOrg;
import com.jslh.model.SysOrgExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface SysOrgMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_org
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	int countByExample(SysOrgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_org
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	int deleteByExample(SysOrgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_org
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_org
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	int insert(SysOrg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_org
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	int insertSelective(SysOrg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_org
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	List<SysOrg> selectByExample(SysOrgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_org
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	SysOrg selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_org
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	int updateByExampleSelective(@Param("record") SysOrg record,
			@Param("example") SysOrgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_org
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	int updateByExample(@Param("record") SysOrg record,
			@Param("example") SysOrgExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_org
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	int updateByPrimaryKeySelective(SysOrg record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_org
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	int updateByPrimaryKey(SysOrg record);
}