package com.jslh.model;

public class SysArea {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_area.code
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_area.name
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_area.code
	 * @return  the value of sys_area.code
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_area.code
	 * @param code  the value for sys_area.code
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_area.name
	 * @return  the value of sys_area.name
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_area.name
	 * @param name  the value for sys_area.name
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}
}