package com.jslh.model;

public class SysOrg {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_org.id
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_org.path
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	private String path;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_org.name
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_org.description
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_org.id
	 * @return  the value of sys_org.id
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_org.id
	 * @param id  the value for sys_org.id
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_org.path
	 * @return  the value of sys_org.path
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_org.path
	 * @param path  the value for sys_org.path
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public void setPath(String path) {
		this.path = path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_org.name
	 * @return  the value of sys_org.name
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_org.name
	 * @param name  the value for sys_org.name
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_org.description
	 * @return  the value of sys_org.description
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_org.description
	 * @param description  the value for sys_org.description
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}