package com.jslh.model;

public class SysRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.id
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.name
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.description
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.id
	 * @return  the value of sys_role.id
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.id
	 * @param id  the value for sys_role.id
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.name
	 * @return  the value of sys_role.name
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.name
	 * @param name  the value for sys_role.name
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.description
	 * @return  the value of sys_role.description
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.description
	 * @param description  the value for sys_role.description
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}