package com.jslh.model;

import java.util.Date;

public class SysUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.id
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.account
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.org_id
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	private Long orgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.password
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.birthday
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.createtime
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.gender
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	private Byte gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.modifytime
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	private Date modifytime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user.status
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	private Byte status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.id
	 * @return  the value of sys_user.id
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.id
	 * @param id  the value for sys_user.id
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.account
	 * @return  the value of sys_user.account
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.account
	 * @param account  the value for sys_user.account
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.org_id
	 * @return  the value of sys_user.org_id
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public Long getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.org_id
	 * @param orgId  the value for sys_user.org_id
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public void setOrgId(Long orgId) {
		this.orgId = orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.password
	 * @return  the value of sys_user.password
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.password
	 * @param password  the value for sys_user.password
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.birthday
	 * @return  the value of sys_user.birthday
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.birthday
	 * @param birthday  the value for sys_user.birthday
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.createtime
	 * @return  the value of sys_user.createtime
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.createtime
	 * @param createtime  the value for sys_user.createtime
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.gender
	 * @return  the value of sys_user.gender
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public Byte getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.gender
	 * @param gender  the value for sys_user.gender
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public void setGender(Byte gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.modifytime
	 * @return  the value of sys_user.modifytime
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public Date getModifytime() {
		return modifytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.modifytime
	 * @param modifytime  the value for sys_user.modifytime
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user.status
	 * @return  the value of sys_user.status
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user.status
	 * @param status  the value for sys_user.status
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}
}