package com.jslh.model;

public class SysUserRoleKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_role.user_id
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_role.role_id
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	private Long roleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_role.user_id
	 * @return  the value of sys_user_role.user_id
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_role.user_id
	 * @param userId  the value for sys_user_role.user_id
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_role.role_id
	 * @return  the value of sys_user_role.role_id
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_role.role_id
	 * @param roleId  the value for sys_user_role.role_id
	 * @mbggenerated  Thu Mar 05 16:54:23 CST 2015
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}
}